services:
  ui:
    build: ./frontend/
    ports:
      - "8080:8080"
    depends_on:
      - api
  api:
    build: ./backend/
    # TODO:
    environment:
      DB_NAME: share_shop
      DB_USER: userAdmin
      DB_PASSWORD: xdb_Admin890!
      DB_HOST: db
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql:8.4
    restart: always
    # TODO:
    environment:
      MYSQL_DATABASE: share_shop
      MYSQL_USER: userAdmin
      MYSQL_PASSWORD: xdb_Admin890!
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  mysql_data:
