services:
  ui:
    build: ./frontend/
    environment:
      MY_APP_API_BASE_URL: http://localhost:8000
    depends_on:
      - api
    ports:
      - "80:80"

  api:
    build: ./backend/
    environment:
      DB_NAME: share_shop
      DB_USER: userAdmin
      DB_PASSWORD: xdb_Admin890!
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: share_shop
      MYSQL_USER: userAdmin
      MYSQL_PASSWORD: xdb_Admin890!
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysql -uuserAdmin -pxdb_Admin890! -e 'SELECT 1;' share_shop"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
